#! bin/sh
sudo easy_install pip
sudo pip install selenium
sudo pip install sortedcontainers
sudo pip install bs4
sudo easy_install BeautifulSoup4
sudo pip install -U nltk
python
import nltk
nltk.download
quit